{
 "title": "Monolith Service",
 "tags": [ "monolith" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Compiled Architecture", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(frontend_requests_total{pod=~\"entrypoint-.*\"}[1m])) by (request_type)",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "P95 Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(frontend_e2e_latency_ms_bucket{pod=~\"entrypoint-.*\"}[1m])) by (le, request_type))",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "P50 Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(frontend_e2e_latency_ms_bucket{pod=~\"entrypoint-.*\"}[1m])) by (le, request_type))",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"entrypoint-.*\", service=\"kube-prometheus-stack-kubelet\"}[1m])) by (pod) / sum(kube_pod_container_resource_limits{namespace=\"default\", pod=~\"entrypoint-.*\", resource=\"cpu\"}) by (pod) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "mebibytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"default\", pod=~\"entrypoint-.*\"}) by (pod) / (1024 * 1024)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P95 Service Call Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(frontend_service_call_latency_ms_bucket{pod=~\"entrypoint-.*\"}[1m])) by (le, service, method))",
     "legendFormat": "{{service}} - {{method}}"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"default\", pod=~\"monolith-deployment-.*\", name=\"monolith-app\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Demo Monolith", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(rate(frontend_requests_total{pod=~\"monolith-deployment-.*\"}[1m])) by (request_type)",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "P95 Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(frontend_e2e_latency_ms_bucket{pod=~\"monolith-deployment-.*\"}[1m])) by (le, request_type))",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "P50 Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(frontend_e2e_latency_ms_bucket{pod=~\"monolith-deployment-.*\"}[1m])) by (le, request_type))",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"monolith-deployment-.*\", service=\"kube-prometheus-stack-kubelet\"}[5m])) by (pod) / sum(kube_pod_container_resource_limits{namespace=\"default\", pod=~\"monolith-deployment-.*\", resource=\"cpu\"}) by (pod) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "mebibytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"default\", pod=~\"monolith-deployment-.*\"}) by (pod) / (1024 * 1024)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P95 Service Call Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(frontend_service_call_latency_ms_bucket{pod=~\"monolith-deployment-.*\"}[1m])) by (le, service, method))",
     "legendFormat": "{{service}} - {{method}}"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"default\", pod=~\"monolith-deployment-.*\", name=\"monolith-app\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}