apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith-deployment
  labels:
    app.kubernetes.io/name: monolith
    discrete.events/experiment: monolift
spec:
  replicas: 16
  selector:
    matchLabels:
      app.kubernetes.io/name: monolith
  template:
    metadata:
      labels:
        app.kubernetes.io/name: monolith
        discrete.events/experiment: monolift
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "monolith"
        dapr.io/app-port: "8080"
    spec:
      containers:
      - name: monolith-app
        imagePullPolicy: Always
        
        image: docker.io/eirn/demo-monolith:dapr
        ports:
        - name: http-app
          containerPort: 8080
        - name: http-metrics
          containerPort: 8084
        env:
        - name: K8S_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: monolith-app
              resource: requests.cpu # Expresses value in millicores
              divisor: "1m"
        - name: K8S_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: monolith-app
              resource: limits.cpu # Expresses value in millicores
              divisor: "1m"
        - name: K8S_MEM_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: monolith-app
              resource: requests.memory # Expresses value in bytes
        - name: K8S_MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: monolith-app
              resource: limits.memory # Expresses value in bytes
        # If using a Kubernetes Secret for the password, it would look like this:
        # - name: REDIS_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: redis-secret # Name of your Secret object
        #       key: password     # Key within the Secret
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "2000m"

