apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: post-store
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: monolith-redis.default.svc.cluster.local:6379
  - name: redisPassword
    value: "redispass"
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: socialgraph-store
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: monolith-redis.default.svc.cluster.local:6379
  - name: redisPassword
    value: "redispass"
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: user-store
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: monolith-redis.default.svc.cluster.local:6379
  - name: redisPassword
    value: "redispass"
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: image-store
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: monolith-redis.default.svc.cluster.local:6379
  - name: redisPassword
    value: "redispass"
