apiVersion: v1
kind: Service
metadata:
  name: monolith-metrics
  labels:
    app.kubernetes.io/name: monolith
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: monolith
  ports:
    - name: http-metrics
      port: 8084
      targetPort: 8084