{
 "title": "Monolith Service",
 "tags": [ "monolith" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(frontend_requests_total[5m])) by (request_type)",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "P95 Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(frontend_e2e_latency_ms_bucket[5m])) by (le, request_type))",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"default\", pod=~\"monolith-deployment-.*\", service=\"kube-prometheus-stack-kubelet\"}[5m])) by (pod) / sum(kube_pod_container_resource_limits{namespace=\"default\", pod=~\"monolith-deployment-.*\", resource=\"cpu\"}) by (pod) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mebibytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"default\", pod=~\"monolith-deployment-.*\"}) by (pod) / (1024 * 1024)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}