apiVersion: v1
kind: Service
metadata:
  name: monolith-service
  labels:
    app.kubernetes.io/name: monolith
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: monolith
  ports:
  - protocol: TCP
    name: http-app
    port: 80
    targetPort: 8080