package codegen

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestWriteArtifactsWritesHeadersAndManifest(t *testing.T) {
	root := t.TempDir()
	plan := &Plan{
		SourceModuleRoot: root,
		ServiceName:      "sanitize-html",
		CutPoint: CutPoint{
			PackagePath: "example.com/app/sanitizer",
			FuncName:    "SanitizeHTML",
			File:        filepath.Join(root, "sanitizer", "sanitizer.go"),
			Line:        12,
		},
		ServerPath:   filepath.Join(root, "monolift_gen", "sanitize-html", "cmd", "sanitize-html", "main.go"),
		ClientPath:   filepath.Join(root, "sanitizer", "monolift_lift_SANITIZE_HTML.go"),
		ManifestPath: filepath.Join(root, "monolift_gen", "sanitize-html", ManifestName),
		Admission: AdmissionVerdict{
			Accepted: true,
			Reasons:  []string{"accepted"},
		},
	}
	artifacts := []Artifact{
		{Path: plan.ClientPath, Kind: "client_stub", Content: []byte("package sanitizer\n")},
		{Path: plan.ServerPath, Kind: "server", Content: []byte("package main\n")},
	}

	manifest, err := WriteArtifacts(plan, artifacts, plan.CutPoint.File)
	if err != nil {
		t.Fatal(err)
	}
	if manifest.PatchedFile != plan.CutPoint.File {
		t.Fatalf("patched file = %s, want %s", manifest.PatchedFile, plan.CutPoint.File)
	}
	for _, path := range []string{plan.ServerPath, plan.ClientPath} {
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		if !strings.HasPrefix(string(data), "// Code generated by monolift "+GeneratorVersion+" for example.com/app/sanitizer.SanitizeHTML; DO NOT EDIT.") {
			t.Fatalf("%s missing generated header:\n%s", path, data)
		}
	}

	data, err := os.ReadFile(plan.ManifestPath)
	if err != nil {
		t.Fatal(err)
	}
	var decoded Manifest
	if err := json.Unmarshal(data, &decoded); err != nil {
		t.Fatal(err)
	}
	if decoded.ServerPath != plan.ServerPath || decoded.StubPath != plan.ClientPath || !decoded.Admission.Accepted {
		t.Fatalf("manifest did not record expected paths/admission: %+v", decoded)
	}
	if len(decoded.Artifacts) != 2 || decoded.Artifacts[0].Path != plan.ServerPath || decoded.Artifacts[1].Path != plan.ClientPath {
		t.Fatalf("manifest artifacts are not deterministic: %+v", decoded.Artifacts)
	}
}

func TestWriteArtifactsRejectsPathsOutsideModuleRoot(t *testing.T) {
	root := t.TempDir()
	plan := &Plan{
		SourceModuleRoot: root,
		ServiceName:      "svc",
		CutPoint: CutPoint{
			PackagePath: "example.com/app/p",
			FuncName:    "Work",
		},
		ManifestPath: filepath.Join(root, ManifestName),
	}
	_, err := WriteArtifacts(plan, []Artifact{
		{Path: filepath.Join(root, "..", "outside.go"), Kind: "server", Content: []byte("package main\n")},
	}, "")
	if err == nil {
		t.Fatal("WriteArtifacts error = nil, want outside-root error")
	}
}

func TestWriteArtifactsDoesNotHeaderDeployArtifacts(t *testing.T) {
	root := t.TempDir()
	plan := &Plan{
		SourceModuleRoot: root,
		ServiceName:      "svc",
		CutPoint: CutPoint{
			PackagePath: "example.com/app/p",
			FuncName:    "Work",
		},
		ManifestPath: filepath.Join(root, ManifestName),
	}
	dockerfile := filepath.Join(root, "monolift_gen", "svc", "Dockerfile.host-svc")
	yamlPath := filepath.Join(root, "monolift_gen", "svc", "manifests", "svc-deployment.yaml")
	artifacts := []Artifact{
		{Path: dockerfile, Kind: "dockerfile_host", Content: []byte("FROM scratch\n")},
		{Path: yamlPath, Kind: "k8s_deployment_host", Content: []byte("apiVersion: apps/v1\n")},
	}
	if _, err := WriteArtifacts(plan, artifacts, ""); err != nil {
		t.Fatal(err)
	}
	for _, item := range []struct {
		path string
		want string
	}{
		{path: dockerfile, want: "FROM scratch\n"},
		{path: yamlPath, want: "apiVersion: apps/v1\n"},
	} {
		data, err := os.ReadFile(item.path)
		if err != nil {
			t.Fatal(err)
		}
		if string(data) != item.want {
			t.Fatalf("%s content = %q, want %q", item.path, data, item.want)
		}
	}
}
