package codegen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func WriteArtifacts(plan *Plan, artifacts []Artifact, patchedFile string) (*Manifest, error) {
	if plan == nil {
		return nil, fmt.Errorf("codegen: nil plan")
	}
	entries, err := writeArtifactFiles(plan, artifacts)
	if err != nil {
		return nil, err
	}
	return writeManifest(plan, entries, patchedFile)
}

func writeArtifactFiles(plan *Plan, artifacts []Artifact) ([]ManifestEntry, error) {
	sort.Slice(artifacts, func(i, j int) bool {
		return artifacts[i].Path < artifacts[j].Path
	})
	entries := make([]ManifestEntry, 0, len(artifacts))
	for _, artifact := range artifacts {
		if err := validateGeneratedPath(plan, artifact.Path); err != nil {
			return nil, err
		}
		content := artifact.Content
		if strings.HasSuffix(artifact.Path, ".go") {
			content = withGeneratedHeader(plan, content)
		}
		if err := writeAtomic(artifact.Path, content, 0644); err != nil {
			return nil, err
		}
		entries = append(entries, ManifestEntry{Path: artifact.Path, Kind: artifact.Kind})
	}
	return entries, nil
}

func writeManifest(plan *Plan, entries []ManifestEntry, patchedFile string) (*Manifest, error) {
	if err := validateGeneratedPath(plan, plan.ManifestPath); err != nil {
		return nil, err
	}
	manifest := Manifest{
		GeneratorVersion: GeneratorVersion,
		ServiceName:      plan.ServiceName,
		Cut: ManifestCut{
			PackagePath: plan.CutPoint.PackagePath,
			Function:    plan.CutPoint.FuncName,
			Receiver:    plan.CutPoint.Receiver,
			File:        plan.CutPoint.File,
			Line:        plan.CutPoint.Line,
		},
		ServerPath:  plan.ServerPath,
		StubPath:    plan.ClientPath,
		PatchedFile: patchedFile,
		Artifacts:   append([]ManifestEntry(nil), entries...),
		Admission:   plan.Admission,
	}
	data, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return nil, err
	}
	data = append(data, '\n')
	if err := writeAtomic(plan.ManifestPath, data, 0644); err != nil {
		return nil, err
	}
	return &manifest, nil
}

func artifactsFromRendered(kind string, files map[string][]byte) []Artifact {
	paths := make([]string, 0, len(files))
	for path := range files {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	artifacts := make([]Artifact, 0, len(paths))
	for _, path := range paths {
		artifacts = append(artifacts, Artifact{Path: path, Kind: kind, Content: files[path]})
	}
	return artifacts
}

func withGeneratedHeader(plan *Plan, content []byte) []byte {
	header := fmt.Sprintf("// Code generated by monolift %s for %s.%s; DO NOT EDIT.\n\n", GeneratorVersion, plan.CutPoint.PackagePath, plan.CutPoint.FuncName)
	if bytes.HasPrefix(content, []byte("// Code generated by monolift ")) {
		return content
	}
	return append([]byte(header), content...)
}

func validateGeneratedPath(plan *Plan, path string) error {
	if path == "" {
		return fmt.Errorf("codegen: generated path is empty")
	}
	if plan == nil || plan.SourceModuleRoot == "" {
		return nil
	}
	absRoot, err := filepath.Abs(plan.SourceModuleRoot)
	if err != nil {
		return err
	}
	absPath, err := filepath.Abs(path)
	if err != nil {
		return err
	}
	rel, err := filepath.Rel(absRoot, absPath)
	if err != nil {
		return err
	}
	if rel == "." || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return fmt.Errorf("codegen: generated path %s is outside source module root %s", path, plan.SourceModuleRoot)
	}
	return nil
}

func writeAtomic(path string, content []byte, perm os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".monolift-*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)
	if _, err := tmp.Write(content); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Chmod(perm); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpPath, path)
}
