E2E_TMP_DIR ?= /tmp/monolift-e2e
E2E_STUBCOMPILER := ./bin/stubcompiler

.PHONY: e2e e2e-reset e2e-update-golden e2e-clean build-stubcompiler

build-stubcompiler:
	go build -o $(E2E_STUBCOMPILER) ./test/e2e/stubcompiler

e2e: build-stubcompiler
	MONOLIFT_E2E=1 go test -tags=e2e -v ./test/e2e/... -timeout=30m

e2e-reset:
	kind delete cluster --name monolift-e2e || true
	kind create cluster --name monolift-e2e --config test/e2e/fixtures/kind-config.yaml

e2e-update-golden: build-stubcompiler
	MONOLIFT_E2E=1 MONOLIFT_E2E_UPDATE_GOLDEN=1 go test -tags=e2e -v ./test/e2e/... -timeout=30m

e2e-clean:
	rm -rf $(E2E_TMP_DIR)/*
